"http://schema.org/Book": "Book"
"http://purl.org/library/Serial": "Serial"
"http://schema.org/CreativeWork": "Creative Work"
"http://schema.org/Article": "Article"
"http://schema.org/MediaObject": "Media Object"
"http://www.productontology.org/id/Video": "Video"
"http://www.productontology.org/id/DVD": "DVD"
"http://schema.org/MusicAlbum": "Music Album"
"http://www.productontology.org/id/Compact_Disc": "Compact Disc"
"http://www.productontology.org/id/VHS": "VHS"
"http://www.productontology.org/id/Audiobook": "Audio Book"
